output   = "models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "db"
  host   = "localhost"
  port   = 5432
  user   = "user"
  pass   = "pass"
  blacklist = ["migrations"]
  sslmode = "disable"