// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChangeRequests string
	RebaseJobs     string
	TMTJobs        string
}{
	ChangeRequests: "change_requests",
	RebaseJobs:     "rebase_jobs",
	TMTJobs:        "tmt_jobs",
}
