// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Customers    string
	InvoiceItems string
	Invoices     string
	Products     string
}{
	Customers:    "customers",
	InvoiceItems: "invoice_items",
	Invoices:     "invoices",
	Products:     "products",
}
