// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// StatusEvent is an object representing the database table.
type StatusEvent struct {
	ID              int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Status          string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	Timestamp       time.Time `boil:"timestamp" json:"timestamp" toml:"timestamp" yaml:"timestamp"`
	ChangeRequestID null.Int  `boil:"change_request_id" json:"change_request_id,omitempty" toml:"change_request_id" yaml:"change_request_id,omitempty"`

	R *statusEventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L statusEventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StatusEventColumns = struct {
	ID              string
	Status          string
	Timestamp       string
	ChangeRequestID string
}{
	ID:              "id",
	Status:          "status",
	Timestamp:       "timestamp",
	ChangeRequestID: "change_request_id",
}

var StatusEventTableColumns = struct {
	ID              string
	Status          string
	Timestamp       string
	ChangeRequestID string
}{
	ID:              "status_events.id",
	Status:          "status_events.status",
	Timestamp:       "status_events.timestamp",
	ChangeRequestID: "status_events.change_request_id",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var StatusEventWhere = struct {
	ID              whereHelperint
	Status          whereHelperstring
	Timestamp       whereHelpertime_Time
	ChangeRequestID whereHelpernull_Int
}{
	ID:              whereHelperint{field: "\"status_events\".\"id\""},
	Status:          whereHelperstring{field: "\"status_events\".\"status\""},
	Timestamp:       whereHelpertime_Time{field: "\"status_events\".\"timestamp\""},
	ChangeRequestID: whereHelpernull_Int{field: "\"status_events\".\"change_request_id\""},
}

// StatusEventRels is where relationship names are stored.
var StatusEventRels = struct {
	ChangeRequest string
}{
	ChangeRequest: "ChangeRequest",
}

// statusEventR is where relationships are stored.
type statusEventR struct {
	ChangeRequest *ChangeRequest `boil:"ChangeRequest" json:"ChangeRequest" toml:"ChangeRequest" yaml:"ChangeRequest"`
}

// NewStruct creates a new relationship struct
func (*statusEventR) NewStruct() *statusEventR {
	return &statusEventR{}
}

func (r *statusEventR) GetChangeRequest() *ChangeRequest {
	if r == nil {
		return nil
	}
	return r.ChangeRequest
}

// statusEventL is where Load methods for each relationship are stored.
type statusEventL struct{}

var (
	statusEventAllColumns            = []string{"id", "status", "timestamp", "change_request_id"}
	statusEventColumnsWithoutDefault = []string{"status"}
	statusEventColumnsWithDefault    = []string{"id", "timestamp", "change_request_id"}
	statusEventPrimaryKeyColumns     = []string{"id"}
	statusEventGeneratedColumns      = []string{}
)

type (
	// StatusEventSlice is an alias for a slice of pointers to StatusEvent.
	// This should almost always be used instead of []StatusEvent.
	StatusEventSlice []*StatusEvent
	// StatusEventHook is the signature for custom StatusEvent hook methods
	StatusEventHook func(context.Context, boil.ContextExecutor, *StatusEvent) error

	statusEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	statusEventType                 = reflect.TypeOf(&StatusEvent{})
	statusEventMapping              = queries.MakeStructMapping(statusEventType)
	statusEventPrimaryKeyMapping, _ = queries.BindMapping(statusEventType, statusEventMapping, statusEventPrimaryKeyColumns)
	statusEventInsertCacheMut       sync.RWMutex
	statusEventInsertCache          = make(map[string]insertCache)
	statusEventUpdateCacheMut       sync.RWMutex
	statusEventUpdateCache          = make(map[string]updateCache)
	statusEventUpsertCacheMut       sync.RWMutex
	statusEventUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var statusEventAfterSelectMu sync.Mutex
var statusEventAfterSelectHooks []StatusEventHook

var statusEventBeforeInsertMu sync.Mutex
var statusEventBeforeInsertHooks []StatusEventHook
var statusEventAfterInsertMu sync.Mutex
var statusEventAfterInsertHooks []StatusEventHook

var statusEventBeforeUpdateMu sync.Mutex
var statusEventBeforeUpdateHooks []StatusEventHook
var statusEventAfterUpdateMu sync.Mutex
var statusEventAfterUpdateHooks []StatusEventHook

var statusEventBeforeDeleteMu sync.Mutex
var statusEventBeforeDeleteHooks []StatusEventHook
var statusEventAfterDeleteMu sync.Mutex
var statusEventAfterDeleteHooks []StatusEventHook

var statusEventBeforeUpsertMu sync.Mutex
var statusEventBeforeUpsertHooks []StatusEventHook
var statusEventAfterUpsertMu sync.Mutex
var statusEventAfterUpsertHooks []StatusEventHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *StatusEvent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *StatusEvent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *StatusEvent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *StatusEvent) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *StatusEvent) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *StatusEvent) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *StatusEvent) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *StatusEvent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *StatusEvent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range statusEventAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStatusEventHook registers your hook function for all future operations.
func AddStatusEventHook(hookPoint boil.HookPoint, statusEventHook StatusEventHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		statusEventAfterSelectMu.Lock()
		statusEventAfterSelectHooks = append(statusEventAfterSelectHooks, statusEventHook)
		statusEventAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		statusEventBeforeInsertMu.Lock()
		statusEventBeforeInsertHooks = append(statusEventBeforeInsertHooks, statusEventHook)
		statusEventBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		statusEventAfterInsertMu.Lock()
		statusEventAfterInsertHooks = append(statusEventAfterInsertHooks, statusEventHook)
		statusEventAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		statusEventBeforeUpdateMu.Lock()
		statusEventBeforeUpdateHooks = append(statusEventBeforeUpdateHooks, statusEventHook)
		statusEventBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		statusEventAfterUpdateMu.Lock()
		statusEventAfterUpdateHooks = append(statusEventAfterUpdateHooks, statusEventHook)
		statusEventAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		statusEventBeforeDeleteMu.Lock()
		statusEventBeforeDeleteHooks = append(statusEventBeforeDeleteHooks, statusEventHook)
		statusEventBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		statusEventAfterDeleteMu.Lock()
		statusEventAfterDeleteHooks = append(statusEventAfterDeleteHooks, statusEventHook)
		statusEventAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		statusEventBeforeUpsertMu.Lock()
		statusEventBeforeUpsertHooks = append(statusEventBeforeUpsertHooks, statusEventHook)
		statusEventBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		statusEventAfterUpsertMu.Lock()
		statusEventAfterUpsertHooks = append(statusEventAfterUpsertHooks, statusEventHook)
		statusEventAfterUpsertMu.Unlock()
	}
}

// One returns a single statusEvent record from the query.
func (q statusEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StatusEvent, error) {
	o := &StatusEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for status_events")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all StatusEvent records from the query.
func (q statusEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (StatusEventSlice, error) {
	var o []*StatusEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to StatusEvent slice")
	}

	if len(statusEventAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all StatusEvent records in the query.
func (q statusEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count status_events rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q statusEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if status_events exists")
	}

	return count > 0, nil
}

// ChangeRequest pointed to by the foreign key.
func (o *StatusEvent) ChangeRequest(mods ...qm.QueryMod) changeRequestQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChangeRequestID),
	}

	queryMods = append(queryMods, mods...)

	return ChangeRequests(queryMods...)
}

// LoadChangeRequest allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (statusEventL) LoadChangeRequest(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStatusEvent interface{}, mods queries.Applicator) error {
	var slice []*StatusEvent
	var object *StatusEvent

	if singular {
		var ok bool
		object, ok = maybeStatusEvent.(*StatusEvent)
		if !ok {
			object = new(StatusEvent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStatusEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStatusEvent))
			}
		}
	} else {
		s, ok := maybeStatusEvent.(*[]*StatusEvent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStatusEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStatusEvent))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &statusEventR{}
		}
		if !queries.IsNil(object.ChangeRequestID) {
			args[object.ChangeRequestID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &statusEventR{}
			}

			if !queries.IsNil(obj.ChangeRequestID) {
				args[obj.ChangeRequestID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`change_requests`),
		qm.WhereIn(`change_requests.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ChangeRequest")
	}

	var resultSlice []*ChangeRequest
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ChangeRequest")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for change_requests")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for change_requests")
	}

	if len(changeRequestAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ChangeRequest = foreign
		if foreign.R == nil {
			foreign.R = &changeRequestR{}
		}
		foreign.R.StatusEvents = append(foreign.R.StatusEvents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ChangeRequestID, foreign.ID) {
				local.R.ChangeRequest = foreign
				if foreign.R == nil {
					foreign.R = &changeRequestR{}
				}
				foreign.R.StatusEvents = append(foreign.R.StatusEvents, local)
				break
			}
		}
	}

	return nil
}

// SetChangeRequest of the statusEvent to the related item.
// Sets o.R.ChangeRequest to related.
// Adds o to related.R.StatusEvents.
func (o *StatusEvent) SetChangeRequest(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ChangeRequest) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"status_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"change_request_id"}),
		strmangle.WhereClause("\"", "\"", 2, statusEventPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ChangeRequestID, related.ID)
	if o.R == nil {
		o.R = &statusEventR{
			ChangeRequest: related,
		}
	} else {
		o.R.ChangeRequest = related
	}

	if related.R == nil {
		related.R = &changeRequestR{
			StatusEvents: StatusEventSlice{o},
		}
	} else {
		related.R.StatusEvents = append(related.R.StatusEvents, o)
	}

	return nil
}

// RemoveChangeRequest relationship.
// Sets o.R.ChangeRequest to nil.
// Removes o from all passed in related items' relationships struct.
func (o *StatusEvent) RemoveChangeRequest(ctx context.Context, exec boil.ContextExecutor, related *ChangeRequest) error {
	var err error

	queries.SetScanner(&o.ChangeRequestID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("change_request_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ChangeRequest = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.StatusEvents {
		if queries.Equal(o.ChangeRequestID, ri.ChangeRequestID) {
			continue
		}

		ln := len(related.R.StatusEvents)
		if ln > 1 && i < ln-1 {
			related.R.StatusEvents[i] = related.R.StatusEvents[ln-1]
		}
		related.R.StatusEvents = related.R.StatusEvents[:ln-1]
		break
	}
	return nil
}

// StatusEvents retrieves all the records using an executor.
func StatusEvents(mods ...qm.QueryMod) statusEventQuery {
	mods = append(mods, qm.From("\"status_events\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"status_events\".*"})
	}

	return statusEventQuery{q}
}

// FindStatusEvent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStatusEvent(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*StatusEvent, error) {
	statusEventObj := &StatusEvent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"status_events\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, statusEventObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from status_events")
	}

	if err = statusEventObj.doAfterSelectHooks(ctx, exec); err != nil {
		return statusEventObj, err
	}

	return statusEventObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *StatusEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no status_events provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(statusEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	statusEventInsertCacheMut.RLock()
	cache, cached := statusEventInsertCache[key]
	statusEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			statusEventAllColumns,
			statusEventColumnsWithDefault,
			statusEventColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(statusEventType, statusEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(statusEventType, statusEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"status_events\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"status_events\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into status_events")
	}

	if !cached {
		statusEventInsertCacheMut.Lock()
		statusEventInsertCache[key] = cache
		statusEventInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the StatusEvent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *StatusEvent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	statusEventUpdateCacheMut.RLock()
	cache, cached := statusEventUpdateCache[key]
	statusEventUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			statusEventAllColumns,
			statusEventPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update status_events, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"status_events\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, statusEventPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(statusEventType, statusEventMapping, append(wl, statusEventPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update status_events row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for status_events")
	}

	if !cached {
		statusEventUpdateCacheMut.Lock()
		statusEventUpdateCache[key] = cache
		statusEventUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q statusEventQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for status_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for status_events")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StatusEventSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), statusEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"status_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, statusEventPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in statusEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all statusEvent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *StatusEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no status_events provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(statusEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	statusEventUpsertCacheMut.RLock()
	cache, cached := statusEventUpsertCache[key]
	statusEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			statusEventAllColumns,
			statusEventColumnsWithDefault,
			statusEventColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			statusEventAllColumns,
			statusEventPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert status_events, could not build update column list")
		}

		ret := strmangle.SetComplement(statusEventAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(statusEventPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert status_events, could not build conflict column list")
			}

			conflict = make([]string, len(statusEventPrimaryKeyColumns))
			copy(conflict, statusEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"status_events\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(statusEventType, statusEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(statusEventType, statusEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert status_events")
	}

	if !cached {
		statusEventUpsertCacheMut.Lock()
		statusEventUpsertCache[key] = cache
		statusEventUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single StatusEvent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *StatusEvent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no StatusEvent provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), statusEventPrimaryKeyMapping)
	sql := "DELETE FROM \"status_events\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from status_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for status_events")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q statusEventQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no statusEventQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from status_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for status_events")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StatusEventSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(statusEventBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), statusEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"status_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, statusEventPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from statusEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for status_events")
	}

	if len(statusEventAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *StatusEvent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindStatusEvent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StatusEventSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := StatusEventSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), statusEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"status_events\".* FROM \"status_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, statusEventPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in StatusEventSlice")
	}

	*o = slice

	return nil
}

// StatusEventExists checks if the StatusEvent row exists.
func StatusEventExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"status_events\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if status_events exists")
	}

	return exists, nil
}

// Exists checks if the StatusEvent row exists.
func (o *StatusEvent) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return StatusEventExists(ctx, exec, o.ID)
}
